server:
  port : 8080

spring:
  application:
    name: math-engine

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always